config/routes.rb
# frozen_string_literal: true

# Routes
Rails.application.routes.draw do
  resources :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'
  get '/notice', to: 'posts#clear_message'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

# Post Model
class Post < ApplicationRecord
  validates :title, presence: true

  has_rich_text :content
end

app/models/user.rb
# frozen_string_literal: true

# User Model
class User < ApplicationRecord
  validates :name, presence: true, length: 2..50
  validates :email, presence: true, uniqueness: true, length: 5..100,
                    format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# Posts Controller
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      format.turbo_stream

      if @post.save
        format.html { redirect_to(posts_path, notice: 'Post was successfully created.') }
        format.json { render(:show, status: :created, location: @post) }
      else
        format.html { render(posts_path, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      format.turbo_stream

      if @post.update(post_params)
        format.html { redirect_to(posts_path, notice: 'Post was successfully updated.') }
        format.json { render(:show, status: :ok, location: @post) }
      else
        format.html { render(posts_path, status: :unprocessable_entity) }
        format.json { render(json: @post.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to(posts_url, notice: 'Post was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users Controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to(user_url(@user), notice: 'User was successfully created.') }
        format.json { render(:show, status: :created, location: @user) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to(user_url(@user), notice: 'User was successfully updated.') }
        format.json { render(:show, status: :ok, location: @user) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @user.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to(users_url, notice: 'User was successfully destroyed.') }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper
module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

# Posts Helper
module PostsHelper
  NOTICE = {
    create: 'Post created successfully',
    update: 'Post updated successfully',
    delete: 'Post deleted successfully',
    error: 'Something went wrong'
  }.freeze

  private_constant :NOTICE

  def notice_stream(message:, status:)
    turbo_stream.replace('notice', partial: 'notice', locals: { notice: NOTICE[message], status: status })
  end

  def form_post_stream(post:)
    turbo_stream.replace('form', partial: 'form', locals: { post: post })
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Users Helper
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atelier</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-300">
    <%= turbo_frame_tag :notice, class: 'w-full' do %>
    <% end %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= turbo_frame_tag dom_id post do %>
  <%= form_with(
    model: post, 
    id: 'form',
    class: "contents",
    html: {
      data: { controller: 'notice', action: 'submit->notice#clear' }
    }
  ) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-100 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :content %>
      <%= form.rich_text_area :content, class: "block shadow rounded-md bg-white border border-gray-100 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-green-500 text-white object-cover shadow font-medium" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_notice.html.erb
<p class="animate-pulse opacity-80 w-full py-2 px-3 bg-<%= status %>-50 mb-5 text-<%= status %>-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id post do %>
  <div class="bg-gray-100 w-full p-4 rounded-md shadow-lg mt-4">
    <h1 class="my-5 text-lg font-bold text-gray-700 text-4xl hover:text-blue-400">
      <%= link_to post.title, post_path(post) %>
    </h1>
    <p class="my-5">
      <%= post.content %>
    </p>

    <div class="w-full mt-2 flex flex-wrap border shadow p-2 rounded-md">
      <p class="flex-1 text-center font-bold text-gray-700">Created at: <%= post.created_at.strftime('%d/%m/%Y') %></p>
    </div>
  </div>
<% end %>

app/views/posts/clear_message.turbo_stream.erb
<%= turbo_stream.replace 'notice' do %>
  <%= turbo_frame_tag :notice %>
<% end %>

app/views/posts/create.turbo_stream.erb
<% if @post.errors.present? %>
  <%= notice_stream(message: :error, status: 'red') %>
  <%= form_post_stream(post: @post) %>
<% else %>
  <%= notice_stream(message: :create, status: 'green') %>

  <%= turbo_stream.replace :new_post do %>
    <%= turbo_frame_tag :new_post %>
  <% end %>
  <%= turbo_stream.prepend 'posts', partial: 'post', locals: { post: @post } %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= notice_stream(message: :delete, status: 'green') %>
<%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag dom_id @post do %>
  <div class="w-full bg-gray-100 p-4 rounded-md mt-5">
    <h1 class="font-bold text-4xl">Editing post</h1>

    <%= render "form", post: @post %>
    <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="bg-gray-300 w-full mt-3">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-gray-900 text-2xl font-bold text-4xl">
      Posts page
    </h1>
    <%= link_to new_post_path, class: "rounded-full px-3 bg-green-500 text-white block font-medium", data: { 'turbo-frame': 'new_post' } do %>
      <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
    <% end %>
  </div>

  <%= turbo_stream_from :posts %>
  <%= turbo_frame_tag :new_post %>

  <div class="flex bg-gray-300 mt-5 p-4 rounded-lg">
    <%= turbo_frame_tag :posts do %>
      <%= render @posts %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag :new_post do %>
  <div class="w-full bg-gray-100 p-4 mt-3 rounded-md shadow-lg">
    <div class="flex justify-between items-center">
      <h1 class="flex text-2xl font-bold text-gray-700 text-4xl">
        Create new post
      </h1>
      <div class="text-sm">
        <%= link_to posts_path do %>
          <svg class="rounded-full px-3 my-4 bg-white w-12 h-12 object-cover shadow" fill="none" stroke="currentColor" viewBox="0 0 23 23" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
        <% end %>
      </div>
    </div>

    <%= render "form", post: @post %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>
<%= turbo_frame_tag dom_id(@post) do %>
  <div class="flex bg-gray-100 rounded-md shadow-lg mb-3 mt-3 p-4">
    <div class="flex items-start w-full px-4 py-6">
      <div class="w-full">
        <div class="flex mb-2 items-center justify-between">
          <h1 class="text-lg font-bold text-gray-900 text-4xl">
            <%= @post.title %>
          </h1>
          <small class="text-sm text-gray-700">
            <%= @post.created_at %>
          </small>
        </div>
        <p class="mb-4 mt-3 text-gray-700 text-sm">
          <%= @post.content %>
        </p>

        <div class="flex justify-between mt-3 px-3">
          <div class="text-sm">
            <%= link_to posts_path do %>
              <svg class="rounded-full px-3 my-4 bg-white w-12 h-12 object-cover shadow" fill="none" stroke="currentColor" viewBox="0 0 23 23" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
            <% end %>
          </div>
          <div class="text-sm">
            <%= link_to edit_post_path(@post) do %>
              <svg class="rounded-full px-3 my-4 bg-white w-12 h-12  object-cover shadow" fill="none" stroke="currentColor" viewBox="0 0 23 23" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path></svg>
            <% end %>
          </div>
          <div class="text-sm">
            <%= button_to post_path(@post), method: :delete, data: { controller: 'confirm', confirm_message_value: 'Deseja remover ?', action: 'click->confirm#dialog' } do %>
              <svg class="rounded-full px-3 my-4 bg-white w-12 h-12 object-cover shadow" fill="none" stroke="currentColor" viewBox="0 0 23 23" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/update.turbo_stream.erb
<% if @post.errors.present? %>
  <%= notice_stream(message: :error, status: 'red') %>
  <%= form_post_stream(post: @post) %>
<% else %>
  <%= notice_stream(message: :update, status: 'green') %>
  <%= turbo_stream.replace dom_id(@post), partial: 'post', locals: { post: @post } %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <div>
      <p>
        <%= user.name %>
      </p>
    </div>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <div>
      <p>
        <%= user.email %>
      </p>
    </div>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Show this user", @user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="users" class="min-w-full">
    <%= render @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to 'Edit this user', edit_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this user', user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to users', users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>